version: "3"
services:
  hres-api:
    build:
      context: ./
    container_name: hres-api
    hostname: hres-api
    ports:
      - "8080:3000"
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
    depends_on:
      - hres-api
